#!/bin/bash

# 描述: 生成 shell wrapper 配置

# 用法:
#   siti init <shell>           - 输出 wrapper 函数配置
#   siti init zsh               - 输出 zsh 配置
#   siti init bash              - 输出 bash 配置
#
# 示例:
#   # 查看配置
#   siti init zsh
#
#   # 添加到 shell 配置
#   eval "$(siti init zsh)" >> ~/.zshrc
#   source ~/.zshrc
#
#   # 或者直接添加
#   siti init zsh >> ~/.zshrc

set -e

SHELL_TYPE="${1:-zsh}"

# 检查参数
case "$SHELL_TYPE" in
  zsh|bash|sh)
    # 支持的 shell
    ;;
  --help|-h|help)
    echo "siti init - 生成 shell wrapper 配置"
    echo ""
    echo "用法:"
    echo "  siti init <shell>           输出 wrapper 函数配置"
    echo "  siti init zsh               输出 zsh 配置（默认）"
    echo "  siti init bash              输出 bash 配置"
    echo ""
    echo "示例:"
    echo "  # 查看配置"
    echo "  siti init zsh"
    echo ""
    echo "  # 添加到 shell 配置"
    echo "  eval \"\$(siti init zsh)\" >> ~/.zshrc"
    echo "  source ~/.zshrc"
    echo ""
    echo "说明:"
    echo "  shell wrapper 使 'siti ai switch' 和 'siti proxy' 等命令"
    echo "  能够修改当前终端的环境变量，无需手动 eval"
    exit 0
    ;;
  *)
    echo "错误: 不支持的 shell 类型: $SHELL_TYPE" >&2
    echo "支持的类型: zsh, bash, sh" >&2
    echo "运行 'siti init --help' 查看帮助" >&2
    exit 1
    ;;
esac

cat << 'EOF'
# siti shell wrapper - generated by siti-cli
siti() {
  local out err_file exit_code
  err_file=$(mktemp)
  out=$(command siti "$@" 2>"$err_file")
  exit_code=$?
  if [ $exit_code -eq 10 ]; then
    eval "$out"
    [ -s "$err_file" ] && cat "$err_file"
  else
    [ -s "$err_file" ] && cat "$err_file" >&2
    echo "$out"
  fi
  rm -f "$err_file"
  return $exit_code
}
EOF
