# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.2/siti-cli_2.0.2_darwin_amd64.tar.gz"
      sha256 "b884451916313003de70b0692ab0cf4ed368f99b8dbdd3cd0c72a43cdc37be23"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.2/siti-cli_2.0.2_darwin_arm64.tar.gz"
      sha256 "243601479a54df765b558a83f2ce3dc7a39f9e0397226fd5c27397facce9cafb"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.2/siti-cli_2.0.2_linux_amd64.tar.gz"
      sha256 "1b9a8b364233ff5302fb41f27eae992a68e7835c554ec737e07c9319023bb457"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.2/siti-cli_2.0.2_linux_arm64.tar.gz"
      sha256 "91ea2295d5d8de7e836f54b5c144668d8a0341fa51c69365494942bfd7ca64a0"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        echo 'eval "$(siti init zsh)"' >> ~/.zshrc
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
