# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.3/siti-cli_2.0.3_darwin_amd64.tar.gz"
      sha256 "61f215adbab1fc50d7e7aee16d1bdcb9328e0185128cf9dc29c1a6d0c47bf445"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.3/siti-cli_2.0.3_darwin_arm64.tar.gz"
      sha256 "4b9fbd121160cc0879983065334411bdbc1113ce2919d23ee5b2036b4ec76e4a"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.3/siti-cli_2.0.3_linux_amd64.tar.gz"
      sha256 "509fd2942c3e7215dbc4077ddff2f6ac28d3652dedcb005c4e3f3f7515518533"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v2.0.3/siti-cli_2.0.3_linux_arm64.tar.gz"
      sha256 "9a90829c2ef4a0f0f9affff380fc1523c374e960fdf627f996275a2f72ada9fe"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        echo 'eval "$(siti init zsh)"' >> ~/.zshrc
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
