# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v3.0.0/siti-cli_3.0.0_darwin_amd64.tar.gz"
      sha256 "26c507f8201eccf74d620ebb0d9febcefe1b521dd1e57f8768649ed97e8be4f3"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v3.0.0/siti-cli_3.0.0_darwin_arm64.tar.gz"
      sha256 "2a57ab707a584af0b04a9db0921720f499fdfcb21cd93acd2e0eec12647329c3"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v3.0.0/siti-cli_3.0.0_linux_amd64.tar.gz"
      sha256 "52700f66d8d3d9b2ec62e59a75fbc5daef31a1004b7d4f01ea36932688b34d19"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/homebrew-siti-cli/releases/download/v3.0.0/siti-cli_3.0.0_linux_arm64.tar.gz"
      sha256 "e93f757d70481f55fd943075ddade89ca0708a5beb63ce4affb5d499ce3ca5b5"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        echo 'eval "$(siti init zsh)"' >> ~/.zshrc
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
