#!/bin/bash

# siti-cli 安装后初始化
# 注意：禁用 set -e，避免权限问题导致整个脚本失败
# set -e

# 统一使用 ~/.siti-cli 作为用户数据目录（commands, config, logs, cache）
SITI_DIR="$HOME/.siti-cli"

echo "正在初始化 siti-cli..."

# 先创建目录，再迁移（避免覆盖已存在的 ~/.siti-cli 如独立安装）
mkdir -p "$SITI_DIR"/{commands,logs,cache,config}

# 迁移旧目录 ~/.siti 到 ~/.siti-cli（调用迁移脚本）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -d "$HOME/.siti" ] && [ -f "$SCRIPT_DIR/migrate-to-unified.sh" ]; then
  SITI_DIR="$SITI_DIR" bash "$SCRIPT_DIR/migrate-to-unified.sh" || true
fi

# 创建配置文件
if [ ! -f "$SITI_DIR/config/siti.conf" ]; then
  cat > "$SITI_DIR/config/siti.conf" << EOF
# siti-cli 配置文件
LOG_LEVEL="info"
LOG_FILE="$HOME/.siti-cli/logs/siti.log"
CACHE_DIR="$HOME/.siti-cli/cache"
USER_COMMANDS_DIR="$HOME/.siti-cli/commands"
EOF
fi

# 补全与 wrapper：先试 .zshrc，失败则 .bashrc
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [ "$rc" = "$HOME/.bashrc" ] && [ ! -f "$rc" ] && continue
  if ! grep -q "siti-cli completion" "$rc" 2>/dev/null; then
    if (touch "$rc" 2>/dev/null && cat >> "$rc" 2>/dev/null) << 'COMPLETE'

# siti-cli completion
if command -v siti >/dev/null 2>&1; then
  [ -f /opt/homebrew/share/zsh/site-functions/_siti ] && fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
  [ -f /usr/local/share/zsh/site-functions/_siti ] && fpath=(/usr/local/share/zsh/site-functions $fpath)
fi
COMPLETE
    then echo "✅ Shell 补全已添加到 $rc"; break
    fi
  else echo "✅ Shell 补全已存在"; break
  fi
done

# 示例命令
if [ ! -f "$SITI_DIR/commands/hello.sh" ]; then
  cat > "$SITI_DIR/commands/hello.sh" << 'EOF'
#!/bin/bash
# 描述: 示例用户自定义命令
name="${1:-World}"
echo "Hello, $name! 这是一个用户自定义命令示例。"
EOF
  chmod +x "$SITI_DIR/commands/hello.sh"
  echo "✅ 已创建示例命令 hello"
fi

write_wrapper() {
  local rc="$1"
  cat >> "$rc" << 'WRAPPER'

# siti shell wrapper - generated by siti-cli
siti() {
  local out err_file exit_code
  err_file=$(mktemp)
  out=$(command siti "$@" 2>"$err_file")
  exit_code=$?
  if [ $exit_code -eq 10 ]; then
    eval "$out"
    [ -s "$err_file" ] && cat "$err_file"
  else
    [ -s "$err_file" ] && cat "$err_file" >&2
    echo "$out"
  fi
  rm -f "$err_file"
  return $exit_code
}
WRAPPER
}

for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [ "$rc" = "$HOME/.bashrc" ] && [ ! -f "$rc" ] && continue
  grep -q "siti shell wrapper" "$rc" 2>/dev/null && { echo "✅ Shell wrapper 已存在"; break; }
  if touch "$rc" 2>/dev/null && write_wrapper "$rc" 2>/dev/null; then
    echo "✅ Shell wrapper 已安装到 $rc（siti ai switch、siti proxy 将在当前终端生效）"; break
  fi
  [ "$rc" = "$HOME/.bashrc" ] && echo "⚠️  无法写入 rc 文件，请运行: eval \"\$(siti init zsh)\" >> ~/.zshrc && source ~/.zshrc" >&2
done

echo ""
echo "✅ 初始化完成，用户数据: $SITI_DIR"
echo "运行 'siti --help' 查看命令"
