package shell

// WrapperFor returns the shell function text for the given shell type.
// This is output by `siti init [zsh|bash|fish]` and sourced by the user's shell config.
//
// Design contract: when exit code is 10, stdout is guaranteed to contain only
// valid shell statements (produced exclusively by shell.Export/Unset/ExportRef/SourceIf).
// The wrapper trusts this contract and evals the full stdout, rather than
// applying a fragile whitelist grep that would silently drop any new shell helpers.
func WrapperFor(shellType string) string {
	switch shellType {
	case "fish":
		return fishWrapper
	default: // zsh, bash, sh
		return posixWrapper
	}
}

// posixWrapper is compatible with zsh and bash.
//
// Exit-code-10 protocol:
//   - stdout: valid shell statements emitted by the Go binary
//   - stderr: human-readable messages (printed directly to terminal)
//
// After eval succeeds we return 0 (not 10) so chaining works:
//
//	siti ai switch && echo ok   # prints "ok" correctly
const posixWrapper = `# siti shell wrapper - generated by siti-cli
# Enables commands like 'siti ai switch' and 'siti proxy on' to modify
# the current shell's environment variables transparently.
siti() {
  local out err_file exit_code
  err_file=$(mktemp)
  out=$(command siti "$@" 2>"$err_file")
  exit_code=$?
  if [ $exit_code -eq 10 ]; then
    [ -n "$out" ] && eval "$out"
    [ -s "$err_file" ] && cat "$err_file" >&2
    rm -f "$err_file"
    return 0
  else
    [ -s "$err_file" ] && cat "$err_file" >&2
    [ -n "$out" ] && echo "$out"
    rm -f "$err_file"
    return $exit_code
  fi
}`

const fishWrapper = `# siti shell wrapper for fish - generated by siti-cli
function siti
  set -l tmp (mktemp)
  set -l out (command siti $argv 2>$tmp)
  set -l code $status
  if test $code -eq 10
    test -n "$out"; and eval $out
    test -s $tmp; and cat $tmp >&2
    rm -f $tmp
    return 0
  else
    test -s $tmp; and cat $tmp >&2
    test -n "$out"; and echo $out
    rm -f $tmp
    return $code
  end
end`
