package shell

// WrapperFor returns the shell function text for the given shell type.
// This is output by `siti init [zsh|bash|fish]` and sourced by the user's shell config.
//
// Design contract: when exit code is 10, stdout is guaranteed to contain only
// valid shell statements (produced exclusively by shell.Export/Unset/ExportRef/SourceIf).
// The wrapper trusts this contract and evals the full stdout, rather than
// applying a fragile whitelist grep that would silently drop any new shell helpers.
func WrapperFor(shellType string) string {
	switch shellType {
	case "fish":
		return fishWrapper
	default: // zsh, bash, sh
		return posixWrapper
	}
}

// posixWrapper is compatible with zsh and bash.
//
// Exit-code-10 protocol:
//   - stdout: valid shell statements emitted by the Go binary
//   - stderr: human-readable messages (printed directly to terminal)
//
// After eval succeeds we return 0 (not 10) so chaining works:
//
//	siti ai switch && echo ok   # prints "ok" correctly
const posixWrapper = `# siti shell wrapper - generated by siti-cli
# Enables commands like 'siti ai switch' and 'siti proxy on' to modify
# the current shell's environment variables transparently.
#
# Exit-code-10 protocol:
#   - The Go binary writes shell statements to $SITI_EVAL_FILE (a temp file)
#     and exits with code 10.
#   - Non-exit-10 commands pass through directly (child processes inherit TTY).
siti() {
  local eval_file exit_code
  eval_file=$(mktemp)
  SITI_EVAL_FILE="$eval_file" command siti "$@"
  exit_code=$?
  if [ $exit_code -eq 10 ]; then
    [ -s "$eval_file" ] && eval "$(cat "$eval_file")"
    rm -f "$eval_file"
    return 0
  fi
  rm -f "$eval_file"
  return $exit_code
}`

const fishWrapper = `# siti shell wrapper for fish - generated by siti-cli
#
# Exit-code-10 protocol:
#   - The Go binary writes shell statements to $SITI_EVAL_FILE (a temp file)
#     and exits with code 10.
#   - Non-exit-10 commands pass through directly (child processes inherit TTY).
function siti
  set -l eval_file (mktemp)
  set -x SITI_EVAL_FILE $eval_file
  command siti $argv
  set -l code $status
  if test $code -eq 10
    test -s $eval_file; and eval (cat $eval_file)
    rm -f $eval_file
    return 0
  end
  rm -f $eval_file
  return $code
end`
